# Generated by Django 4.0.2 on 2022-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title_xpath', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_xpath', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('links_xpath', models.CharField(max_length=100)),
                ('start_url', models.CharField(max_length=100)),
                ('body_xpath', models.CharField(max_length=100)),
                ('image_xpath', models.CharField(max_length=100)),
                ('date_xpath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.source')),
            ],
        ),
    ]
