# Generated by Django 4.0.2 on 2022-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='body_xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='date_xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='image_xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='links_xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_xpath',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='title_xpath',
            field=models.CharField(max_length=200),
        ),
    ]
